import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ffb77d",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#f9e287",
        "inverse-primary": "#904d00",
        "on-primary-fixed": "#2f1500",
        "on-tertiary-fixed": "#221b00",
        "surface-container-highest": "#353534",
        "tertiary": "#dcc66e",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#dbc2b0",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#6e3900",
        "primary-fixed": "#ffdcc3",
        "surface-bright": "#3a3939",
        "outline-variant": "#554336",
        "on-secondary": "#532200",
        "on-tertiary-fixed-variant": "#534600",
        "on-error": "#690005",
        "outline": "#a38c7c",
        "on-secondary-fixed-variant": "#763300",
        "secondary": "#ffb68e",
        "secondary-fixed": "#ffdbca",
        "surface-dim": "#131313",
        "on-tertiary-container": "#4b3f00",
        "primary": "#ffb77d",
        "on-primary": "#4d2600",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353534",
        "secondary-container": "#ab4c00",
        "surface-container": "#201f1f",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "primary-fixed-dim": "#ffb77d",
        "tertiary-container": "#bfab56",
        "surface": "#131313",
        "error-container": "#93000a",
        "primary-container": "#d97707",
        "secondary-fixed-dim": "#ffb68e",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#dcc66e",
        "on-surface": "#e5e2e1",
        "on-tertiary": "#3a3000",
        "on-secondary-container": "#ffe2d5",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed": "#331200",
        "on-primary-container": "#432100",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "unit": "4px",
        "container-max": "1440px",
        "gutter": "24px",
      },
      fontFamily: {
        "headline-md": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "mono-data": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "mono-data": ["14px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
